#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'
	newline = true

	[[blocks.segments]]
		type = 'path'
		style = 'plain'
		background = 'transparent'
		foreground = 'p:green'
		template = '{{ .Path }}'

		[blocks.segments.properties]
			style = 'full'

	[[blocks.segments]]
		type = 'git'
		style = 'plain'
		foreground = 'p:purple'
		background = 'transparent'
		template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}'

		[blocks.segments.properties]
			commit_icon = '@'
			fetch_status = true



[[blocks]]
	type = 'rprompt'
	overflow = 'hidden'

	[[blocks.segments]]
		type = 'executiontime'
		style = 'plain'
		foreground = 'p:yellow'
		background = 'transparent'
		template = '{{ div .Ms 1000 }}s'

		[blocks.segments.properties]
			threshold = 5000

	[[blocks.segments]]
		type = 'python'
		style = 'plain'
		foreground = 'p:orange'
		background = 'transparent'
		template = '{{ if .Venv }}{{ .Venv | printf " %s (venv)"}}{{end}}' 



[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

	[[blocks.segments]]
		type = 'text'
		style = 'plain'
		foreground_templates = [
			"{{if gt .Code 0}}p:red{{end}}",
			"{{if eq .Code 0}}p:purple{{end}}",
		]
		background = 'transparent'
		template = '❯'	
	
[transient_prompt]
	foreground_templates = [
		"{{if gt .Code 0}}p:red{{end}}",
		"{{if eq .Code 0}}p:purple{{end}}",
	]
	background = 'transparent'
	template = '❯'
	

[palette]
orange = "#FF847C"
green = "#99B898"
red = "#E84A5F"
yellow = "#FECEAB"
